[package]
name = "proc_watcher"
version = "0.1.6"
authors = ["sourcepirate <sathyanarrayanan@yandex.com>"]
edition = "2018"

[dependencies]
procfs = "0.5.3"
log = "0.4.7"
rusoto_cloudwatch = "0.40.0"
chrono = "0.4.7"